docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  #services:
  #  - docker:dind
  before_script:
    - docker login -u "hsazarmsa" -p "hena78705044" docker.io
  script:
    - docker build -t myapp .
    - docker push index.docker.io/hsazarmsa/ie_backend
  only:
    - master

