docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "hsazarmsa" -p "hena78705044"
  script:
    - docker build -t ie_backend .
    - docker push hsazarmsa/ie_backend
  only:
    - master
