docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  #services:
  #  - docker:dind
  before_script:
    - docker login -u "hsazarmsa" -p "hena78705044" registery.hub.docker.com/repository/docker/hsazarmsa/ie_backend
  script:
    - docker build -t myapp .
    - docker push hsazarmsa/ie_backend
  only:
    - master

