docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  #services:
  #  - docker:dind
  before_script:
    - sudo docker login -u "hsazarmsa" -p "hena78705044" $CI_REGISTRY
  script:
    - sudo docker build -t myapp .
    - sudo docker push hsazarmsa/ie_backend
  only:
    - master

