docker-build-master:
  # Official docker image.
  image: myapp
  stage: build
  #services:
  #  - docker:dind
  before_script:
    - docker login -u "hsazarmsa" -p "hena78705044" $CI_REGISTRY
  script:
    - docker build -t myapp .
    - docker push hsazarmsa/ie_backend
  only:
    - master

