docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "hsazarmsa" -p "hena78705044"
  script:
    - docker build -t hsazarmsa/ie_backend .
    - docker push hsazarmsa/ie_backend
    - docker build -t hsazarmsa/ie_database ./my-sql
    - docker push hsazarmsa/ie_database
  after_script:
    - docker logout
  only:
    - master
