---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: hosna-fatemeh-ns
type: Opaque
data:
  mysql-password: c3VwZXJzZWNyZXQ=
  mysql-root-password: c3VwZXJzZWNyZXQ=
  mysql-user: cm9vdA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
  namespace: hosna-fatemeh-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: manual

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
data:
  test.sh: |
    #!/bin/bash
    mysql -psupersecret </docker-entrypoint-initdb.d/loghme.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: hosna-fatemeh-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
#        - name: init
#          image: "k8s.gcr.io/busybox"
#          command: ["/bin/sh","-c","mysql -psupersecret </docker-entrypoint-initdb.d/loghme.sql"]
#          volumeMounts:
#            - name: mysql-data
#              mountPath: "/var/lib/mysql"
#          resources:
#              limits:
#                memory: "20Mi"
#                cpu: "0.01"
        - name: mysql
          image: hsazarmsa/ie_database:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
            - name: init-script
              mountPath: /script/test.sh
              subPath: test.sh
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
          resources:
            limits:
              memory: "480Mi"
              cpu: "0.29"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
        - name: init-script
          configMap:
            name: init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: hosna-fatemeh-ns
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30010